// AUTO-GENERATED by scripts/generate-locale-registry.mjs — do not edit manually.
// Run `bun run i18n:locales` after adding/removing a file in web/locales/.
import en_US from "./en-US.json";
import ru_RU from "./ru-RU.json";
import zh_CN from "./zh-CN.json";

export const catalogs: Record<string, Record<string, string>> = {
  "en-US": en_US,
  "ru-RU": ru_RU,
  "zh-CN": zh_CN,
};
